"""empty message

Revision ID: 0b4cd3488a4d
Revises: ee6cb8192667
Create Date: 2025-05-28 17:59:12.783532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4cd3488a4d'
down_revision = 'ee6cb8192667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reminders', schema=None) as batch_op:
        batch_op.drop_column('pinned')

    # ### end Alembic commands ###
