"""Correct error -hopefully-

Revision ID: 0c7e26ae38b9
Revises: d9fc5cd8c3c0
Create Date: 2025-01-30 08:58:54.506376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7e26ae38b9'
down_revision = 'd9fc5cd8c3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reminders', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
