"""empty message

Revision ID: 15a71aa7ee88
Revises: 0b4cd3488a4d
Create Date: 2025-05-30 19:15:59.929344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a71aa7ee88'
down_revision = '0b4cd3488a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fid'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Friendship')
    # ### end Alembic commands ###
