"""empty message

Revision ID: 27a12e80b3b5
Revises: 2826a25eac30
Create Date: 2025-05-25 18:21:17.413136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a12e80b3b5'
down_revision = '2826a25eac30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronote_username', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('pronote_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('pronote_url')
        batch_op.drop_column('pronote_username')

    # ### end Alembic commands ###
