"""empty message

Revision ID: 2826a25eac30
Revises: ecce786cfd95
Create Date: 2025-05-23 21:19:03.511786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2826a25eac30'
down_revision = 'ecce786cfd95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('pronote_password')
        batch_op.drop_column('pronote_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronote_username', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('pronote_password', sa.VARCHAR(length=250), nullable=True))

    # ### end Alembic commands ###
