"""empty message

Revision ID: 5ab823b80593
Revises: 27a12e80b3b5
Create Date: 2025-05-27 07:27:05.803943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab823b80593'
down_revision = '27a12e80b3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Otp', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
