"""empty message

Revision ID: 8ae2603b0e54
Revises: 70f4e177e0ad
Create Date: 2025-03-03 21:07:45.305815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae2603b0e54'
down_revision = '70f4e177e0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronote_tag_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('pronote_tag_id')

    # ### end Alembic commands ###
