"""empty message

Revision ID: ecce786cfd95
Revises: 945c7cc7ca9f
Create Date: 2025-05-17 10:11:54.398062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecce786cfd95'
down_revision = '945c7cc7ca9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Token', schema=None) as batch_op:
        batch_op.drop_column('expiry')

    # ### end Alembic commands ###
