"""empty message

Revision ID: ee6cb8192667
Revises: aaa48c0bc368
Create Date: 2025-05-28 06:49:07.978896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6cb8192667'
down_revision = 'aaa48c0bc368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Otp', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
